name: React Front-End Unit Testing
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.15.0"

      # Install required deps for action
      - name: Install Frontend Dependencies
        run: npm install
        working-directory: frontend_employeemanager

      # Finally, run our tests
      - name: Execute Unit Tests
        run: npm run test
        working-directory: frontend_employeemanager
